---
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Guardfile
    - Rakefile

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Style/RedundantSelf:
  Exclude:
    - lib/train-rest/auth_handler.rb
